[project]
name = "geff"
version = "0.1.0"
description = "Reference implementation of the Graph Exchange File Format"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "zarr<3.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
